<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-SDHJL4S" name="com.Niki_Old.TestCases.AboutAndUpdate" tests="7" failures="1" timestamp="03 Sep 2019 11:05:53 GMT" time="81.227" errors="0">
  <testcase name="verifyUpdate" time="1.669" classname="com.Niki_Old.TestCases.AboutAndUpdate"/>
  <testcase name="verifyAboutLinkFunctionality" time="25.943" classname="com.Niki_Old.TestCases.AboutAndUpdate">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Niki: Online Recharge, Utility Bill Payment &amp; more] but found [Niki: Online Recharges, Bill Payments &amp; more]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Niki: Online Recharge, Utility Bill Payment & more] but found [Niki: Online Recharges, Bill Payments & more]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.Niki_Old.TestCases.AboutAndUpdate.verifyAboutLinkFunctionality(AboutAndUpdate.java:196)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- verifyAboutLinkFunctionality -->
  <testcase name="verifyAboutPageElements" time="0.348" classname="com.Niki_Old.TestCases.AboutAndUpdate"/>
  <testcase name="verifyHowNikiWorksLink" time="9.985" classname="com.Niki_Old.TestCases.AboutAndUpdate"/>
  <testcase name="verifyTermsAndConditionLink" time="11.873" classname="com.Niki_Old.TestCases.AboutAndUpdate"/>
  <testcase name="verifyPartnerLink" time="21.899" classname="com.Niki_Old.TestCases.AboutAndUpdate"/>
  <testcase name="verifyAboutLink" time="9.510" classname="com.Niki_Old.TestCases.AboutAndUpdate"/>
</testsuite> <!-- com.Niki_Old.TestCases.AboutAndUpdate -->
